name: "Submit New Nano-Banana 2 Image Example ✨"
description: "Share an awesome Nano-Banana 2 image example and its prompt you found to help enrich our collection! Maintainers will assist in organizing and adding it."
title: "New Example: <Please provide a short, descriptive title for the example, e.g., New Example: Paper Craft Style Emoji>"
labels: ["contribution", "image"]
body:
  - type: markdown
    attributes:
      value: |
        **Thank you for sharing an awesome example! Please fill out the following information as detailed as possible to help us add it 👇**

  - type: textarea
    id: preview_image
    attributes:
      label: Please upload or paste the example image
      description: "Drag & drop or paste the image here (Recommended ≤1 MB)"
      placeholder: "Drag & drop image file here or paste screenshot"
    validations:
      required: true

  - type: input
    id: source_link
    attributes:
      label: Example Source Link
      description: "Share the link to the original post (e.g., tweet, blog post, etc.) for attribution and reference."
      placeholder: "https://x.com/xxxx/status/123..."
    validations:
      required: true

  - type: input
    id: author_link
    attributes:
      label: Original Author Profile Link
      description: "Share the original author's profile page (e.g., Twitter/X, GitHub, personal website, etc.)"
      placeholder: "https://x.com/xxxx"
    validations:
      required: true

  - type: textarea
    id: prompt
    attributes:
      label: Prompt
      description: "The full prompt used to generate the image (in its original language - English, Chinese, or any other language)"
      placeholder: "e.g. Create a high-resolution 3D render of [emoji] as an inflated cushion..."
    validations:
      required: true

  - type: textarea
    id: reference_images
    attributes:
      label: Reference Images (Optional)
      description: "If you used reference images for generation, please provide the URLs or describe them. You can include multiple reference images."
      placeholder: "e.g., https://example.com/ref1.png, https://example.com/ref2.png, or describe the reference images used"
    validations:
      required: false